version: "3.9"
services:
  backend:
    image: ${REGISTRY}/${BACKEND_IMAGE}:${BACKEND_TAG:-latest}
    ports:
      - 5000:5000

  frontend:
    image: ${REGISTRY}/${FRONTEND_IMAGE}:${FRONTEND_TAG:-latest}
